kovu/urls.py
from django.contrib import admin
from django.urls import path,include
# from kovu.orders.views import createorder

from orders.views import (
    create_item_form
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('orders.urls','orders'),namespace ='orders')),

    path('htmx/itemform',create_item_form,name = "form-item"),

    
]

orders/urls.py
from django.urls import path
from  . import views

app_name = "orders"

urlpatterns = [
    
    path('products/',views.ProductList.as_view(),name = 'product-list'),
    path('products/create',views.CreateProduct.as_view(),name = 'create-product'),
    
    path('orders/create-item/',views.create_item,name = 'item-create'),


    path('orders/',views.OrderList.as_view(),name = 'order-list'),
    path('orders/<int:pk>', views.OrderDetail.as_view(), name="order-details"),
    path('orders/create/', views.CreateOrder.as_view(), name="order-create"),


]

orders/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=7,decimal_places=2)

    def __str__(self):
        return self.name





class Order(models.Model):
    customer_name = models.CharField(max_length=200)
    customer_phone = models.CharField(max_length=200)
    address = models.CharField(max_length=400,null=True,blank = True)
    location = models.URLField(max_length=1000)
    extra_details = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
       ordering =  ['-updated','-created']

    def __str__(self):
        return str(self.id)

    @property
    def total_order(self):

        orderitems = OrderItem.objects.filter(order_id = self.id)
        sum = 0 
        for orderitem in orderitems:
            sum = (sum + orderitem.price)
        return sum

    @property
    def total_qty(self):
        orderitems = OrderItem.objects.filter(order_id = self.id)
        totalquantity = 0 
        for orderitem in orderitems:
            totalquantity = (totalquantity + orderitem.quantity)
        return totalquantity




class OrderItem(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default = 1, blank=True,null=True)

    @property
    def price(self):
        return self.quantity * self.product.price

    def __str__(self):
        return str(self.order)

    

orders/forms.py
from winreg import QueryInfoKey
from django.forms import ModelForm,inlineformset_factory
from .models import Product,Order,OrderItem
from django import forms

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

class OrderItemForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = ['product','quantity']

        
OrderItemFormset = inlineformset_factory(Order,OrderItem,form = OrderItemForm)

orders/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy


from .models import Product,OrderItem,Order
from .forms import ProductForm,OrderItemFormset,OrderForm,OrderItemForm
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView


from django.forms import inlineformset_factory
from django.db import transaction


class CreateProduct(CreateView):
    model = Product
    form_class = ProductForm
    template_name = "orders/create-product.html"
    success_url = reverse_lazy('orders:product_list')



class ProductList(ListView):
    model = Product
    template_name = "orders/product_list.html"
    context_object_name = "products"


class CreateOrder(CreateView):
    model = Order
    form_class = OrderForm 
    template_name = "orders/create-order.html"


    



def create_item(request):
    
    form = OrderItemForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            item = form.save(commit=False)
            item.save()
            return redirect("order_list")

    context = {"form":form}

    return render(request,"orders/create-order-item.html",context)

    
    

def create_item_form(request):
    context = {"form":OrderItemForm()}


    return render(request,"orders/partials/new-items.html",context)

# class OrderCreate(CreateView):
#     model = Order
#     fields = ['customer_name','customer_phone','address','location','extra_details']
#     template_name = "orders/create-order.html"
#     success_url = reverse_lazy('orders:order_list')

#     def get_context_data(self, **kwargs):
#         data =  super(OrderCreate,self).get_context_data(**kwargs)
#         if self.request.POST:
#             data['items'] = OrderItemFormset(self.request.POST)
#         else:
#             data['items'] = OrderItemFormset()
#         return data

#     def form_valid(self, form):
#         context = self.get_context_data()
#         items = context['items']

#         with transaction.atomic():
#             self.object = form.save()

#             if items.is_valid():
#                 items.instance = self.object
#                 items.save()

#         return super(OrderCreate,self).form_valid(form)




class OrderDetail(DetailView):
    model = Order
    template_name = "orders/view-order.html"



class OrderList(ListView):
    model = Order
    template_name = "orders/order-list.html"
    context_object_name = 'orders'

orders/templates/orders/create-order-item.html
{% extends 'base.html' %}
<script src="https://unpkg.com/htmx.org@1.7.0"></script>


{% block content %}

  
<form method = 'POST'>
    {% csrf_token %}





    <button hx-get="{% url 'form-item' %}" hx-swap= "beforeend" hx-target="#itemforms" name="itemforms">
        add new item
    </button>

    <button hx-delete="{% url 'form-item' %}" hx-swap="innerHTML" hx-target="#itemforms">
        delete item
    </button>


    <div id="itemforms" >

    </div >

    

    <button type="submit">
        add order items
    </button>
</form>

   

{% endblock content %}

   

orders/templates/orders/create-order.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">

    {%csrf_token%}

    {% for field in form %}
        <label>{{field.label}}</label>
        <div name="fields">
            <p>
                {{field}}
            </p>
            
        </div>

        
    

    {% endfor %}

    <button type="submit">create order</button>


</form>


{% endblock content %}

orders/templates/orders/create-product.html
{% extends 'base.html' %}

{% block content %}



{% endblock content %}

orders/templates/orders/order-list.html
{% extends 'base.html' %}

{% block content %}

<div>


    <div>
        <table>
            <thead>
                <tr>
                    <th>Customer</th>
                    <th>Phone number</th>
                    <th>location</th>
                    <th>Total</th>
                </tr>
                
                
                
            </thead>

            <tbody>

                {%for order in orders %}
                    <tr>
                        <td><a href = ' {% url "orders:order-details" order.id %}' >
                            {{order.customer_name | title}}
                        </a></td>
                        <td>{{order.customer_phone}}</td>
                        <td> {{order.address}} </td>
                        <td> {{order.total_order}} </td>
                        
                    </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>


</div>

{% endblock content %}

orders/templates/orders/partials/new-items.html
{% extends 'base.html' %}

{%block content%}

<!-- <div hx-target="this" hx-swap="outerHTML"> -->

    <form method="POST">
        {%csrf_token%}
        {{form}}
    </form>

<!-- </div> -->


{%endblock content%}

orders/templates/orders/product-list.html
{% extends 'base.html' %}

{% block content %}

{% endblock content %}

orders/templates/orders/view-order.html
{% extends 'base.html' %}

{% block content %}

<table>

    <thead>
        <tr>
            <th>Item</th>
            <th>qty</th>
            <th>price</th>
        </tr>
    </thead>

    <tbody>

        {% for orderitem in order.orderitem_set.all  %}

                <tr>
                    <td>{{ orderitem.product }}</td>
                    <td> {{orderitem.quantity }} </td>
                    <td> {{orderitem.price }} </td>

                </tr>

        {% endfor %}



    </tbody>




</table>


{% endblock content %}

templates/base.html
<!DOCTYPE html>

<html>
    <head>


        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        
        <script src="https://unpkg.com/htmx.org@1.7.0"></script>
        
    </head>
    <body>
       
        
        {% include 'navbar.html' %}


        {% block content %}

        {% endblock content %}

        

        <script>
            document.body.addEventListener('htmx:configRequest', (event) => {
                event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
            })
        </script>


        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'orders:order-create' %}">create order</a>
        <a class="nav-item nav-link" href="{%url 'orders:order-list'%}">Order List</a>
        <a class="nav-item nav-link" href="{%url 'orders:create-product'%}">add new product</a>
        <a class="nav-item nav-link disabled" href="#">Disabled</a>
      </div>
    </div>
  </nav>